#pragma once
#define CFG_TUSB_MCU OPT_MCU_STM32F4
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 1
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0
#define CFG_TUD_HID_EP_BUFSIZE 16
#define TUD_OPT_HIGH_SPEED 0
#define TUSB_DESC_CONFIG_ATT_REMOTE_WAKEUP 0x20
#define HID_ITF_PROTOCOL_NONE 0
