#pragma once

#define OPT_MCU_STM32F4 1
#define OPT_OS_NONE 1
#define OPT_MODE_FULL_SPEED 1
#define CFG_TUSB_MCU OPT_MCU_STM32F4
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUH_CDC 1
#define CFG_TUH_MSC 1
#define CFG_TUH_HID 1
#define CFG_TUH_HUB 0
#define CFG_TUH_MIDI 0
#define CFG_TUH_VENDOR 0
#define CFG_TUH_INTERFACE_MAX 6
#define CFG_TUH_ENDPOINT_MAX 8
#define CFG_TUH_ENUMERATION_BUFSIZE 256
#define CFG_TUH_CONTROL_PENDING_QUEUE_SZ 4
#define CFG_TUH_TASK_QUEUE_SZ 8
#define BOARD_TUH_RHPORT 0
#define BOARD_TUH_MAX_SPEED OPT_MODE_FULL_SPEED
